image: python:3

stages:
- lint
- build
- test

flake8:
   stage: lint
   script:
     - pip install flake8
     - flake8 src

.docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  tags:
    - kubernetes
  script:
    - docker build -t ${IMAGE} .
    - echo ${IMAGE}
    - docker push ${IMAGE}

image-master:
  extends: .docker
  only:
    - master
  variables:
    IMAGE: ${IMAGE_REPOSITORY}:${CI_PIPELINE_IID}_master

image-develop:
  extends: .docker
  except:
    - master
  variables:
    IMAGE: ${IMAGE_REPOSITORY}:${CI_PIPELINE_IID}_develop

pytest:
  stage: test
  script:
     - pip install pytest
     - pytest --cov versiongen

local-run:
  stage: test
  script:
     - src/run.py -o src/version.json
     - cat src/version.json

validate:
  stage: test
  image: ${IMAGE_REPOSITORY}:${CI_PIPELINE_IID}_master
  only:
    - master
  script:
     - src/run.py -o src/version.json
     - cat src/version.json
  artifacts:
    paths:
    - src/version.json
