image: python:3-alpine

stages:
- lint
- test
- build


flake8:
   stage: lint
   script:
     - pip install flake8
     - flake8 src

pytest:
  stage: test
  script:
     - pip install pytest-cov
     - pytest
  artifacts:
    paths:
    - htmlcov

local-run:
  stage: test
  script:
     - mkdir out
     - versiongen/generate.py -o out/version.json
     - apk --update add jq
     - cat out/version.json | jq .

.docker:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  tags:
    - kubernetes
  script:
    - docker build -t ${IMAGE} .
    - echo ${IMAGE}
    - docker push ${IMAGE}

image-master:
  extends: .docker
  only:
    - master
  variables:
    IMAGE: ${IMAGE_REPOSITORY}:${CI_PIPELINE_IID}_master

image-develop:
  extends: .docker
  except:
    - master
  variables:
    IMAGE: ${IMAGE_REPOSITORY}:${CI_PIPELINE_IID}_develop

pages:
  stage: build
  script:
    - mkdir public
    - cp -r out/ public/
  artifacts:
    paths:
    - public
  only:
  - master
