image: python:3

stages:
- lint
- build
- test


flake8:
   stage: lint
   script:
     - pip install flake8
     - flake8 src

local:
  stage: test
  script:
     - src/run.py
     - cat version.json

docker:
  stage: test
  image: jrottenberg/versiongen
  script:
     - src/run.py
     - cat version.json
  artifacts:
    paths:
    - version.json
