variables:
- group: videotoolsbuild-dockerhub
- name: DOCKER
  value: jrottenberg/versiongen

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'


  steps:
  - script: |
      python -m pip install flake8
      flake8 .
    displayName: 'Run lint tests'

  - script: |
      pip install pytest-cov
      pytest tests --doctest-modules
    displayName: 'Test with pytest'

- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'


  steps:
  - bash: |
      docker build -t ${DOCKER}:${BUILD_BUILDNUMBER} .
    displayName: Build docker image
  # - bash: |
  #     versiongen/generate.py
  #     cat version.json
  #   displayName: Test image
  - bash: |
      docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
      docker info
      docker push ${DOCKER}:${BUILD_BUILDNUMBER}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Push docker image
    env:
      DOCKER_PASSWORD: $(docker.password)
