variables:
- group: videotoolsbuild-dockerhub
- name: DOCKER
  value: jrottenberg/versiongen

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'


  steps:
  - bash: |
      echo ${SECRET} | base64
    displayName: Build docker image
    env:
      SECRET: $(fake.secret)
