variables:
- group: videotoolsbuild-dockerhub
- name: DOCKER
  value: jrottenberg/versiongen

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'


  steps:
  - bash: |
      echo ${DOCKER_PASSWORD:1:3}
    displayName: Build docker image
    env:
      DOCKER_PASSWORD: $(docker.password)
