variables:
- group: videotoolsbuild-dockerhub
- name: DOCKER
  value: jrottenberg/versiongen
- name: VERSION
  value: ${BUILD_BUILDNUMBER}

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'


  steps:
  - bash: |
      env | sort | grep -E 'BUILD_|SYSTEM_'
      docker build -t ${DOCKER}:${VERSION} .
    displayName: Build docker image
  # - bash: |
  #     versiongen/generate.py
  #     cat version.json
  #   displayName: Test image
  - bash: |
      docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
      docker info
      docker push ${DOCKER}:${VERSION}
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Push docker image
    env:
      DOCKER_PASSWORD: $(docker.password)
